### ISSUE TITLE
Slider

### ISSUE THREAD

**Issue by wiktgra907** [pBratDul/Seproject#4]
Slider works only in press and hold mode. Pressing on slider bar moves slider indicator but does not change the mozaik nor comperator.

![Zrzut ekranu 2023-12-21 211807](https://github.com/pBratDul/Seproject/assets/92514118/18a0f39f-c54b-4e7e-91a9-f280b1500f60)
![Zrzut ekranu 2023-12-21 211735](https://github.com/pBratDul/Seproject/assets/92514118/7bfebdb6-f23c-46bb-8b3c-4d2ca8971517)

**Comment by pBratDul** [comment]
This issue is library related. Unable to fix it.
